# Generated by Django 3.0.7 on 2020-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0003_dataset_urutan'),
    ]

    operations = [
        migrations.CreateModel(
            name='proses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=225)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('kluster', models.IntegerField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='urutan',
        ),
    ]
