# Generated by Django 3.0.7 on 2020-08-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0004_auto_20200807_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proses',
            name='nama',
        ),
        migrations.AddField(
            model_name='proses',
            name='dataset_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
