# Generated by Django 3.0.7 on 2020-08-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0005_auto_20200807_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proses',
            name='index',
        ),
        migrations.RemoveField(
            model_name='proses',
            name='x',
        ),
        migrations.RemoveField(
            model_name='proses',
            name='y',
        ),
    ]
