# Generated by Django 3.0.7 on 2020-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0008_auto_20200810_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proses',
            name='y',
        ),
        migrations.AddField(
            model_name='proses',
            name='index_kluster',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
