# Generated by Django 3.0.7 on 2020-08-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0009_auto_20200810_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proses',
            old_name='x',
            new_name='hasil',
        ),
    ]
