# Generated by Django 3.0.7 on 2020-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0011_remove_proses_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=225)),
                ('alamat_sekolah', models.TextField(max_length=225)),
                ('biaya', models.IntegerField()),
                ('lat', models.CharField(max_length=225)),
                ('lng', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='dataset',
        ),
        migrations.DeleteModel(
            name='hasil',
        ),
        migrations.DeleteModel(
            name='klaster',
        ),
        migrations.DeleteModel(
            name='proses',
        ),
    ]
