# Generated by Django 3.0.7 on 2020-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0012_auto_20200825_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(max_length=225)),
                ('jenis_kelamin', models.CharField(max_length=225)),
                ('tempat_lahir', models.CharField(max_length=225)),
                ('tangal_lahir', models.DateField()),
                ('user', models.CharField(max_length=225)),
                ('gaji_pokok', models.IntegerField()),
                ('asal_sekola', models.CharField(max_length=225)),
                ('alamat_siswa', models.TextField()),
                ('lat', models.CharField(max_length=225)),
            ],
        ),
    ]
