# Generated by Django 3.0.7 on 2020-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sekolah',
            name='lng',
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='alamat_sekolah',
            field=models.TextField(),
        ),
    ]
