# Generated by Django 3.0.7 on 2020-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzy', '0004_auto_20200825_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=225)),
                ('alamat_sekolah', models.TextField()),
                ('biaya', models.IntegerField()),
                ('jarak', models.IntegerField()),
                ('user', models.CharField(max_length=225)),
            ],
        ),
    ]
