# Generated by Django 3.0.7 on 2020-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzy', '0006_proses_bobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proses',
            name='bobot',
            field=models.FloatField(),
        ),
    ]
